server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://capstone-db.crqlyooh7jfa.ap-northeast-2.rds.amazonaws.com/testDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: master
    password: Capstone123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace